language: python

python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "pypy"

env:
  - PIP_USE_MIRRORS=true DEPS="kid genshi"

matrix:
  include:
    - python: "3.3"
      env: DEPS="genshi"
  exclude:
    - python: "3.3"
      env: PIP_USE_MIRRORS=true DEPS="kid genshi"

install:
  - "pip install $DEPS"

script: "python setup.py test"
